//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hikaya.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HikayaDBEntities : DbContext
    {
        public HikayaDBEntities()
            : base("name=HikayaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FeedbackMessage> FeedbackMessages { get; set; }
        public virtual DbSet<SavedStory> SavedStories { get; set; }
        public virtual DbSet<Story> Stories { get; set; }
        public virtual DbSet<StoryPlot> StoryPlots { get; set; }
    }
}
